### ISSUE TITLE
please auto-create a mat. view of all files created/changed in the last 7 days

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/slurm-pwalk#4]
SELECT
  file_metadata.owner,
  file_metadata.filename,
  file_metadata.fileextension,
  file_metadata.uid,
  file_metadata.gid,
  file_metadata.st_size,
  file_metadata.atime,
  file_metadata.mtime,
  file_metadata.ctime
FROM
  file_metadata
WHERE
  (file_metadata.mtime > extract(epoch from now() - INTERVAL '7 DAYS')) OR
  (file_metadata.ctime > extract(epoch from now() - INTERVAL '7 DAYS'))
ORDER BY
  file_metadata.st_size DESC

**Comment by bmcgough** [comment]
This is implemented, but untested. I'll check it after the next run and close if successful.

The view is called 'last_7_days_changes'.
